# This file was generated by GoReleaser. DO NOT EDIT.
cask "lovli-cli" do
  name "lovli-cli"
  desc "Use the Lovli URL shortening service in your terminal"
  homepage "https://github.com/callmesangio/lovli-cli"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lovli"

  on_macos do
    on_intel do
      url "https://github.com/callmesangio/lovli-cli/releases/download/#{version}/lovli-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "94ee98d798768cda64bbcaf14262bf800d6f409815e3a46c7f27ec065052dcb6"
    end
    on_arm do
      url "https://github.com/callmesangio/lovli-cli/releases/download/#{version}/lovli-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "26f4f539eeb9daa45f790a5beb0c3b19d481e84dcd69726eba638a014998e64a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/callmesangio/lovli-cli/releases/download/#{version}/lovli-cli_#{version}_linux_amd64.tar.gz"
      sha256 "31199fac6fddf49315e91147c202d224e2881d2626d3bf947a75a07b48fbfa2a"
    end
  end

  # No zap stanza required
end
